### PR TITLE
Add license_file: LICENSE to meta.yml

### PR DESCRIPTION
**Pull request by janschulz**
Seems that is needed in latest conda-forge: https://github.com/conda-forge/staged-recipes/pull/1354

### CODE REVIEW

**Comment by jakirkham** [comment]
So you will need a build number bump to in order to ensure the package includes the license.

**Comment by jakirkham** [comment]
Weird. CircleCI seems to never have shown up. 😕

**Comment by jakirkham** [comment]
Let's see if that helps.

**Comment by janschulz** [comment]
Lets see if we this time have more luck with getting packages uploaded... #2

**Comment by janschulz** [comment]
Still no circle-CI PR build :-/

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/status/issues/8 ?

**Pull request merged**
