### PR TITLE
Twine 1.9.1

### PR DESCRIPTION
**Pull request by janschulz**

### CODE REVIEW

**Comment by jakirkham** [comment]
May want to bump the build number given some of these have already been released.

**Comment by janschulz** [comment]
Already prepared... waiting for appveyor to see if it finishes

**Comment by jakirkham** [comment]
Hmm...no CircleCI. 😕 Can you please double check your GitHub user settings to make sure CircleCI is enabled? Also may be worth trying to sign into CircleCI with your GitHub account once for good measure.

**Comment by jakirkham** [comment]
Once we get that resolved, it might be worth looking at using [`noarch: python`]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ) here.

**Comment by janschulz** [comment]
I've no clue about circleci. Up to now I never needed to do anything. When I log in it all looks ok. Do I have to enable it somewhere?

**Comment by jakirkham** [comment]
Can you please double check that it is authorized in your GitHub settings? Probably under OAuth Apps.

**Comment by janschulz** [comment]
Yes, circle CI is there: 

screenshot from 2017-09-26 22-32-11

**Comment by jakirkham** [comment]
Could you please try revoking it and readding it?

**Comment by janschulz** [comment]
I've revoked and readded it

**Comment by janschulz** [comment]
I'm kind of inclined to merge this and hope for the best...

**Comment by jakirkham** [comment]
TBH we have seen CircleCI not show up before. Though it occurs so infrequently that it is difficult to track what the fix was or if some new issue is occurring. Someone was able to [revoke their token]( https://github.com/conda-forge/staged-recipes/pull/1090#issuecomment-233786173 ) successfully. Maybe worth giving that a try? 😬

So I was going to suggest using [`noarch: python`]( https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages ). However that [only runs on CircleCI]( https://conda-forge.org/docs/meta.html#building-noarch-packages ). So it is kind of hard to tell if it worked if we can't get CircleCI to build for your PR. 😕

**Pull request merged**
